# Generated by Django 5.1.1 on 2024-10-04 12:50

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Maktab',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nomi', models.CharField(max_length=100)),
                ('manzil', models.CharField(max_length=255)),
                ('tashkil_topgan_yili', models.IntegerField()),
            ],
        ),
    ]
