# Generated by Django 5.1.1 on 2024-10-05 13:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('maktab', '0005_course_student'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='student',
            name='courses',
        ),
        migrations.DeleteModel(
            name='Post',
        ),
        migrations.DeleteModel(
            name='Course',
        ),
        migrations.DeleteModel(
            name='Student',
        ),
    ]
