# Generated by Django 5.1.1 on 2024-10-05 14:55

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('maktab', '0006_remove_student_courses_delete_post_delete_course_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Application',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('description', models.TextField()),
                ('application_file', models.FileField(upload_to='applications/')),
            ],
        ),
    ]
